name: continuous-delivery

on:
  push:
    branches: [main]

jobs:
  semver-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
      - uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@2.12.0.1
        name: semver & changelog
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
          version-prefix: "v"